# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\x12\ttranslate\"O\n\x0e\x44\x65tectLanguage\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x17\n\nconfidence\x18\x02 \x01(\x02H\x00\x88\x01\x01\x42\r\n\x0b_confidence\"i\n\x0eTranslatedText\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t\x12#\n\x16\x64\x65tected_language_code\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x19\n\x17_detected_language_code\"M\n\x08Language\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x19\n\x0c\x64isplay_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_display_name\"<\n\x12SupportedLanguages\x12&\n\tlanguages\x18\x01 \x03(\x0b\x32\x13.translate.Language\"\xad\x01\n\x11TranslateTextData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1d\n\x10source_lang_code\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10target_lang_code\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x61pi_type\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x13\n\x11_source_lang_codeB\x13\n\x11_target_lang_codeB\x0b\n\t_api_type\"_\n\x14TranslateTextRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1c.translate.TranslateTextData\"\x98\x01\n\x15TranslateTextResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12)\n\x06result\x18\x02 \x01(\x0b\x32\x19.translate.TranslatedText\x12\x1a\n\rfrom_api_type\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03msg\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x10\n\x0e_from_api_typeB\x06\n\x04_msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTLANGUAGE']._serialized_start=30
  _globals['_DETECTLANGUAGE']._serialized_end=109
  _globals['_TRANSLATEDTEXT']._serialized_start=111
  _globals['_TRANSLATEDTEXT']._serialized_end=216
  _globals['_LANGUAGE']._serialized_start=218
  _globals['_LANGUAGE']._serialized_end=295
  _globals['_SUPPORTEDLANGUAGES']._serialized_start=297
  _globals['_SUPPORTEDLANGUAGES']._serialized_end=357
  _globals['_TRANSLATETEXTDATA']._serialized_start=360
  _globals['_TRANSLATETEXTDATA']._serialized_end=533
  _globals['_TRANSLATETEXTREQUEST']._serialized_start=535
  _globals['_TRANSLATETEXTREQUEST']._serialized_end=630
  _globals['_TRANSLATETEXTRESPONSE']._serialized_start=633
  _globals['_TRANSLATETEXTRESPONSE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
